export const categories = [
  {
    id: "electronics",
    name: "Electronics",
    image: "/assets/blutooth.png",
    productCount: 125,
  },
  {
    id: "clothing",
    name: "Clothing",
    image: "/assets/clothing.jpg",
    productCount: 89,
  },
  {
    id: "home",
    name: "Home & Kitchen",
    image: "/assets/knifeset.png",
    productCount: 76,
  },
  {
    id: "beauty",
    name: "Beauty",
    image: "/assets/beauty.png",
    productCount: 54,
  },
  {
    id: "mobiles",
    name: "mobiles",
    image: "/assets/mobile.png",
    productCount: 44,
  },
  {
    id: "toys",
    name: "toys",
    image: "/assets/toys.png",
    productCount: 44,
  },
  {
    id: "furnitures",
    name: "Furnitures",
    image: "/assets/furnitures.png",
    productCount: 44,
  },
  {
    id: "auto",
    name: "Auto",
    image: "/assets/auto5.png",
    productCount: 44,
  },
  {
    id: "fashion",
    name: "fashion",
    image: "/assets/fashion.png",
    productCount: 44,
  },
];

export const products = [
  // Electronics
  {
    id: "1",
    name: "Wireless Headphones",
    price: 99.99,
    discount: 20,
    rating: 4.5,
    seller: "AudioTech",
    image: "/assets/headphone2.jpeg",
    category: "electronics",
  },
  {
    id: "2",
    name: "Game Controller",
    price: 49.99,
    rating: 4.3,
    seller: "GamerzHub",
    image: "/assets/gamecontroller.png",
    category: "electronics",
  },
  {
    id: "3",
    name: "Bluetooth Speaker",
    price: 29.99,
    discount: 15,
    rating: 4.5,
    seller: "SoundBlast",
    image: "/assets/blutooth.png",
    category: "electronics",
  },
  {
    id: "4",
    name: "USB-C Cable",
    price: 6.49,
    rating: 4.1,
    seller: "CableCraft",
    image: "/assets/usb-c.png",
    category: "electronics",
  },
  {
    id: "5",
    name: "Portable Power Bank",
    price: 24.99,
    discount: 10,
    rating: 4.6,
    seller: "PowerMax",
    image: "/assets/powerbank.png",
    category: "electronics",
  },

  // Clothing
  {
    id: "6",
    name: "Cotton T-Shirt",
    price: 19.99,
    rating: 4.2,
    seller: "Fashion",
    image: "/assets/clothing.jpg",
    category: "clothing",
  },
  {
    id: "7",
    name: "Denim Jeans",
    price: 39.99,
    rating: 4.0,
    seller: "DenimCo",
    image: "/assets/denimjeans.png",
    category: "clothing",
  },
  {
    id: "8",
    name: "Hoodie Sweatshirt",
    price: 29.99,
    rating: 4.3,
    seller: "ComfyWear",
    image: "/assets/clothing.jpg",
    category: "clothing",
  },
  {
    id: "9",
    name: "Formal Shirt",
    price: 24.99,
    rating: 4.1,
    seller: "UrbanStyle",
    image: "/assets/shirt.png",
    category: "clothing",
  },
  {
    id: "10",
    name: "Summer Shorts",
    price: 14.99,
    rating: 4.4,
    seller: "Fashion",
    image: "/assets/shorts.png",
    category: "clothing",
  },

  // Home & Kitchen
  {
    id: "11",
    name: "Smart LED Bulb",
    price: 12.99,
    rating: 4.3,
    seller: "BrightTech",
    image: "/assets/smartbulb.png",
    category: "home",
  },
  {
    id: "12",
    name: "Kitchen Knife Set",
    price: 34.99,
    rating: 4.5,
    seller: "ChefTools",
    image: "/assets/knifeset.png",
    category: "home",
  },
  {
    id: "13",
    name: "Electric Kettle",
    price: 19.99,
    rating: 4.2,
    seller: "HomeEase",
    image: "/assets/electric Kettle.png",
    category: "home",
  },
  {
    id: "14",
    name: "Spice Rack",
    price: 22.49,
    rating: 4.6,
    seller: "KitchenPro",
    image: "/assets/electric Kettle.png",
    category: "home",
  },
  {
    id: "15",
    name: "Wall Clock",
    price: 15.99,
    rating: 4.0,
    seller: "TickTock",
    image: "/assets/clock.png",
    category: "home",
  },

  // Beauty
  {
    id: "16",
    name: "Face Cream",
    price: 9.99,
    rating: 4.4,
    seller: "GlowUp",
    image: "/assets/cream.png",
    category: "beauty",
  },
  {
    id: "17",
    name: "Hair Serum",
    price: 12.49,
    rating: 4.3,
    seller: "ShineCo",
    image: "/assets/beauty.png",
    category: "beauty",
  },
  {
    id: "18",
    name: "Lipstick Set",
    price: 14.99,
    rating: 4.1,
    seller: "ColorMate",
    image: "/assets/lipstick.png",
    category: "beauty",
  },
  {
    id: "19",
    name: "Compact Powder",
    price: 11.99,
    rating: 4.2,
    seller: "GlowUp",
    image: "/assets/beauty.png",
    category: "beauty",
  },
  {
    id: "20",
    name: "Eyeliner Pen",
    price: 6.99,
    rating: 4.5,
    seller: "StyleLine",
    image: "/assets/lipstick.png",
    category: "beauty",
  },

  // Mobiles
  {
    id: "21",
    name: "Smartphone A1",
    price: 299.99,
    rating: 4.7,
    seller: "MobileMart",
    image: "/assets/mobile.png",
    category: "mobiles",
  },
  {
    id: "22",
    name: "Smartphone B2",
    price: 249.99,
    rating: 4.5,
    seller: "MobileWorld",
    image: "/assets/m2.png",
    category: "mobiles",
  },
  {
    id: "23",
    name: "Smartphone C3",
    price: 199.99,
    rating: 4.3,
    seller: "Techie",
    image: "/assets/m3.png",
    category: "mobiles",
  },
  {
    id: "24",
    name: "Smartphone D4",
    price: 329.99,
    rating: 4.6,
    seller: "SmartStore",
    image: "/assets/mobile.png",
    category: "mobiles",
  },
  {
    id: "25",
    name: "Smartphone E5",
    price: 279.99,
    rating: 4.4,
    seller: "GadgetHub",
    image: "/assets/m3.png",
    category: "mobiles",
  },

  // Toys
  {
    id: "26",
    name: "Building Blocks",
    price: 15.99,
    rating: 4.8,
    seller: "ToyLand",
    image: "/assets/toys.png",
    category: "toys",
  },
  {
    id: "27",
    name: "Remote Car",
    price: 29.99,
    rating: 4.5,
    seller: "ToyZone",
    image: "/assets/car.png",
    category: "toys",
  },
  {
    id: "28",
    name: "Doll Set",
    price: 18.99,
    rating: 4.6,
    seller: "KidsWorld",
    image: "/assets/toy3.png",
    category: "toys",
  },
  {
    id: "29",
    name: "Toy Gun",
    price: 14.99,
    rating: 4.3,
    seller: "ToyMania",
    image: "/assets/toy4.png",
    category: "toys",
  },
  {
    id: "30",
    name: "Puzzle Cube",
    price: 6.99,
    rating: 4.2,
    seller: "PuzzleKing",
    image: "/assets/toy5.png",
    category: "toys",
  },

  // Furnitures
  {
    id: "31",
    name: "Wooden Chair",
    price: 59.99,
    rating: 4.4,
    seller: "HomeWood",
    image: "/assets/furniture1.png",
    category: "furnitures",
  },
  {
    id: "32",
    name: "Dining Table",
    price: 129.99,
    rating: 4.5,
    seller: "UrbanLiving",
    image: "/assets/furniture2.png",
    category: "furnitures",
  },
  {
    id: "33",
    name: "Bookshelf",
    price: 79.99,
    rating: 4.2,
    seller: "FurniCo",
    image: "/assets/furniture3.png",
    category: "furnitures",
  },
  {
    id: "34",
    name: "Sofa Set",
    price: 299.99,
    rating: 4.6,
    seller: "ComfortZone",
    image: "/assets/furniture4.png",
    category: "furnitures",
  },
  {
    id: "35",
    name: "TV Stand",
    price: 89.99,
    rating: 4.3,
    seller: "HomeStyle",
    image: "/assets/furniture1.png",
    category: "furnitures",
  },

  // Auto
  {
    id: "36",
    name: "Car Vacuum Cleaner",
    price: 24.99,
    rating: 4.4,
    seller: "AutoGear",
    image: "/assets/auto1.png",
    category: "auto",
  },
  {
    id: "37",
    name: "Car Seat Cover",
    price: 39.99,
    rating: 4.5,
    seller: "RideComfort",
    image: "/assets/auto2.png",
    category: "auto",
  },
  {
    id: "38",
    name: "Mobile Holder",
    price: 9.99,
    rating: 4.3,
    seller: "CarTech",
    image: "/assets/auto3.png",
    category: "auto",
  },
  {
    id: "39",
    name: "Car Perfume",
    price: 6.99,
    rating: 4.2,
    seller: "FreshRide",
    image: "/assets/gamecontroller.png",
    category: "auto",
  },
  {
    id: "40",
    name: "Dashboard Cover",
    price: 19.99,
    rating: 4.1,
    seller: "AutoStyle",
    image: "/assets/auto5.png",
    category: "auto",
  },

  // Fashion
  {
    id: "41",
    name: "Stylish Watch",
    price: 49.99,
    discount: 10,
    rating: 4.4,
    seller: "TimeZone",
    image: "/assets/fahion1.png",
    category: "fashion",
  },
  {
    id: "42",
    name: "Sunglasses",
    price: 19.99,
    rating: 4.3,
    seller: "StyleHub",
    image: "/assets/fashion2.png",
    category: "fashion",
  },
  {
    id: "43",
    name: "Leather Belt",
    price: 14.99,
    rating: 4.5,
    seller: "Fashionista",
    image: "/assets/fashion3.png",
    category: "fashion",
  },
  {
    id: "44",
    name: "Fashion Wallet",
    price: 24.99,
    rating: 4.2,
    seller: "StyleCo",
    image: "/assets/fashion4.png",
    category: "fashion",
  },
  {
    id: "45",
    name: "Silk Scarf",
    price: 17.99,
    rating: 4.6,
    seller: "Glamour",
    image: "/assets/fashion5.png",
    category: "fashion",
  },
];
